# Generated by Django 4.2.3 on 2024-09-23 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_item_name', models.CharField(max_length=500, verbose_name='ชื่อรายการงบ')),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='งบประมาณได้รับจัดสรร')),
                ('operating_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='งบดำเนินการ')),
                ('procurement_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='งบประมาณซื้อจ้าง')),
                ('contract_sign_date', models.DateField(verbose_name='วันลงนามสัญญาจ้าง')),
                ('contract_end_date', models.DateField(verbose_name='วันสิ้นสุดสัญญา')),
                ('item_type', models.CharField(choices=[('main_item', 'หัวข้อหลัก'), ('sub_item', 'หัวข้อย่อย'), ('budget_item', 'รายการงบ')], default='main_item', max_length=50, verbose_name='ประเภทของรายการงบ')),
                ('sub_item_type', models.CharField(choices=[('none', 'ไม่มี'), ('sub_by_item', 'ย่อยรายรายการ'), ('sub_by_month', 'ย่อยรายเดือน'), ('sub_by_day', 'ย่อยรายวัน')], default='none', max_length=50, verbose_name='ประเภทของรายการย่อย')),
                ('sort_number', models.CharField(max_length=255, verbose_name='หมายเลขลำดับ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=255, verbose_name='ปีงบประมาณ')),
                ('department', models.CharField(max_length=255, verbose_name='กลุ่มงาน')),
                ('section', models.CharField(max_length=255, verbose_name='กองงาน')),
                ('office', models.CharField(max_length=255, verbose_name='สำนักงาน')),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='งบประมาณได้รับจัดสรร')),
                ('operating_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='งบดำเนินการ')),
                ('procurement_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='งบประมาณซื้อจ้าง')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_budget_years', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เพิ่มข้อมูล')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_budget_years', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไขข้อมูล')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=500, verbose_name='ชื่อแผนงาน')),
                ('plan_code', models.CharField(max_length=100, verbose_name='รหัสแผนงาน')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='งบประมาณได้รับจัดสรร')),
                ('operating_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='งบดำเนินการ')),
                ('procurement_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='งบประมาณซื้อจ้าง')),
                ('contract_sign_date', models.DateField(verbose_name='วันลงนามสัญญาจ้าง')),
                ('contract_end_date', models.DateField(verbose_name='วันสิ้นสุดสัญญา')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('sort_order', models.IntegerField(default=500, verbose_name='ลำดับการจัดเรียง')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_plans', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เพิ่มข้อมูล')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_budget.budgetyear', verbose_name='ปีงบประมาณ')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_plans', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไขข้อมูล')),
            ],
        ),
        migrations.CreateModel(
            name='TypeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type_name', models.CharField(max_length=255, verbose_name='ชื่อประเภทใบแจ้งหนี้')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_invoice_types', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เพิ่มข้อมูล')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_invoice_types', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไขข้อมูล')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=500, verbose_name='ชื่อโครงการ')),
                ('project_code', models.CharField(max_length=100, verbose_name='รหัสโครงการ')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='งบประมาณได้รับจัดสรร')),
                ('operating_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='งบดำเนินการ')),
                ('procurement_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='งบประมาณซื้อจ้าง')),
                ('contract_sign_date', models.DateField(verbose_name='วันลงนามสัญญาจ้าง')),
                ('contract_end_date', models.DateField(verbose_name='วันสิ้นสุดสัญญา')),
                ('project_status', models.CharField(choices=[('planning', 'กำลังวางแผน'), ('in_progress', 'กำลังดำเนินการ'), ('completed', 'เสร็จสิ้น'), ('paused', 'ระงับชั่วคราว'), ('canceled', 'ยกเลิก')], default='planning', max_length=50, verbose_name='สถานะโครงการ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('sort_order', models.IntegerField(default=500, verbose_name='ลำดับการจัดเรียง')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_projects', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เพิ่มข้อมูล')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_budget.budgetyear', verbose_name='ปีงบประมาณ')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_budget.plan', verbose_name='แผนงาน')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_projects', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไขข้อมูล')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'มกราคม'), (2, 'กุมภาพันธ์'), (3, 'มีนาคม'), (4, 'เมษายน'), (5, 'พฤษภาคม'), (6, 'มิถุนายน'), (7, 'กรกฎาคม'), (8, 'สิงหาคม'), (9, 'กันยายน'), (10, 'ตุลาคม'), (11, 'พฤศจิกายน'), (12, 'ธันวาคม')], verbose_name='เดือน')),
                ('year', models.PositiveIntegerField(verbose_name='ปี')),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='แผนสำหรับเดือนนั้น')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ผลที่ได้สำหรับเดือนนั้น')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('budget_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_budget.budgetitem', verbose_name='รายการงบ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_monthly_plans', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เพิ่มข้อมูล')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_monthly_plans', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไขข้อมูล')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255, verbose_name='เลขที่ใบแจ้งหนี้')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='วันที่แจ้งหนี้')),
                ('total_amount_due', models.PositiveIntegerField(default=0, verbose_name='รวมเงินที่ต้องชำระ')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='วันที่อนุมัติ')),
                ('approver_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ผู้ขออนุมัติ')),
                ('contractor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อผู้รับจ้าง')),
                ('details', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('invoice_month', models.PositiveSmallIntegerField(choices=[(1, 'มกราคม'), (2, 'กุมภาพันธ์'), (3, 'มีนาคม'), (4, 'เมษายน'), (5, 'พฤษภาคม'), (6, 'มิถุนายน'), (7, 'กรกฎาคม'), (8, 'สิงหาคม'), (9, 'กันยายน'), (10, 'ตุลาคม'), (11, 'พฤศจิกายน'), (12, 'ธันวาคม')], default=1, verbose_name='รายการงบเดือน')),
                ('invoice_year', models.PositiveIntegerField(default=2567, verbose_name='รายการงบปี')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('budget_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_budget.budgetitem', verbose_name='รายการงบ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_invoice', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เพิ่มข้อมูล')),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_budget.budgetyear', verbose_name='ปีงบประมาณ')),
                ('invoice_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_budget.typeinvoice', verbose_name='ประเภทใบแจ้งหนี้')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_invoice', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไขข้อมูล')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_original', models.ImageField(upload_to='uploads/images/original/%Y/%m/%d/', verbose_name='รูปภาพประกอบ')),
                ('file', models.ImageField(upload_to='uploads/images/%Y/%m/%d/', verbose_name='รูปภาพประกอบ')),
                ('file_name_original', models.CharField(max_length=255, verbose_name='ชื่อไฟล์เดิม')),
                ('file_type', models.CharField(max_length=50, verbose_name='ประเภทไฟล์')),
                ('file_size', models.PositiveIntegerField(verbose_name='ขนาดไฟล์')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('order', models.PositiveIntegerField(default=500, verbose_name='Order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_images', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เพิ่มข้อมูล')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_budget.invoice')),
            ],
            options={
                'verbose_name': 'รูปภาพประกอบ',
                'verbose_name_plural': 'รูปภาพประกอบ',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/files/%Y/%m/%d/', verbose_name='ไฟล์ที่เกี่ยวข้อง')),
                ('file_name_original', models.CharField(max_length=255, verbose_name='ชื่อไฟล์เดิม')),
                ('file_type', models.CharField(max_length=50, verbose_name='ประเภทไฟล์')),
                ('file_size', models.PositiveIntegerField(verbose_name='ขนาดไฟล์')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_files', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เพิ่มข้อมูล')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_budget.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='ชื่อกลุ่มของรายการงบ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_categories', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เพิ่มข้อมูล')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_categories', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไขข้อมูล')),
            ],
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_budget.category', verbose_name='กลุ่มของรายการงบ'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_budget_items', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เพิ่มข้อมูล'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='main_budget_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_budget.budgetitem', verbose_name='รายการงบหลัก'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_budget.project', verbose_name='โครงการ'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_budget_items', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไขข้อมูล'),
        ),
    ]
