# Generated by Django 4.2.3 on 2024-09-19 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='ปีงบประมาณ')),
                ('work_group', models.CharField(max_length=255, verbose_name='กลุ่มงาน')),
                ('office', models.CharField(max_length=255, verbose_name='กองงาน')),
                ('office_unit', models.CharField(max_length=255, verbose_name='สำนักงาน')),
                ('income_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='งบประมาณได้รายได้จักสรร')),
                ('operational_expense', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='งบดำเนินการ')),
                ('procurement_expense', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='งบประมาณ จัดซื้อ/จ้าง')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='ชื่อรายการงบ')),
                ('income_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='งบประมาณได้รายได้จักสรร')),
                ('procurement_expense', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='งบประมาณ จัดซื้อ/จ้าง')),
                ('group', models.CharField(max_length=255, verbose_name='กลุ่มรายการงบ')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255, verbose_name='ชื่อประเภทใบแจ้งหนี้')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255, verbose_name='ชื่อแผนงาน')),
                ('plan_code', models.CharField(max_length=100, verbose_name='รหัสแผนงาน')),
                ('income_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='งบประมาณได้รายได้จักสรร')),
                ('operational_expense', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='งบดำเนินการ')),
                ('procurement_expense', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='งบประมาณ จัดซื้อ/จ้าง')),
                ('contract_start_date', models.DateField(verbose_name='วันลงนามสัญญาจ้าง')),
                ('contract_end_date', models.DateField(verbose_name='วันสิ้นสุดสัญญา')),
                ('annual_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_budget.annualbudget', verbose_name='ปีงบประมาณ')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='ชื่อโครงการ')),
                ('project_code', models.CharField(max_length=100, verbose_name='รหัสโครงการ')),
                ('income_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='งบประมาณได้รายได้จักสรร')),
                ('operational_expense', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='งบดำเนินการ')),
                ('procurement_expense', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='งบประมาณ จัดซื้อ/จ้าง')),
                ('contract_start_date', models.DateField(verbose_name='วันลงนามสัญญาจ้าง')),
                ('contract_end_date', models.DateField(verbose_name='วันสิ้นสุดสัญญา')),
                ('annual_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_budget.annualbudget', verbose_name='ปีงบประมาณ')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_budget.plan', verbose_name='แผนงาน')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='เดือน')),
                ('year', models.IntegerField(verbose_name='ปี')),
                ('progress', models.TextField(verbose_name='แผน')),
                ('budget_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_budget.budgetitem', verbose_name='รายการงบ')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255, verbose_name='เลขที่ใบแจ้งหนี้')),
                ('invoice_date', models.DateField(verbose_name='วันที่ใบแจ้งหนี้')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='รวมสินค้าชิ้นราคารวม')),
                ('vat', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ภาษีมูลค่าเพิ่ม')),
                ('payer_name', models.CharField(max_length=255, verbose_name='ชื่อผู้อนุมัติ/ผู้จ่ายเงิน')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='ชื่อผู้รับจ้าง')),
                ('annual_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_budget.annualbudget', verbose_name='ปีงบประมาณ')),
            ],
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_budget.project', verbose_name='โครงการ'),
        ),
        migrations.CreateModel(
            name='AttachedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255, verbose_name='ชื่อเอกสารแนบ')),
                ('document_image', models.ImageField(upload_to='documents/', verbose_name='รูปภาพประกอบ')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_budget.invoice', verbose_name='เอกสารแนบ')),
            ],
        ),
    ]
