# Generated by Django 4.2.3 on 2024-09-20 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'รูปภาพประกอบ', 'verbose_name_plural': 'รูปภาพประกอบ'},
        ),
        migrations.AddField(
            model_name='image',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_images', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เพิ่มข้อมูล'),
        ),
        migrations.AddField(
            model_name='image',
            name='file_name_original',
            field=models.CharField(default=1, max_length=255, verbose_name='ชื่อไฟล์เดิม'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='file_size',
            field=models.PositiveIntegerField(default=1, verbose_name='ขนาดไฟล์'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='file_type',
            field=models.CharField(default=1, max_length=50, verbose_name='ประเภทไฟล์'),
            preserve_default=False,
        ),
    ]
